package com.app.pustakam.android.screen

interface TaskCode
enum class AUTH : TaskCode{
    LOGIN, SIGNUP
}
enum class NOTES_CODES  : TaskCode {
    GET_NOTES, INSERT, DELETE, UPDATE, READ
}
enum class CANVAS_CODES : TaskCode {
    READ_CANVAS, READ_VIEWPORT, SAVE_NODE, SAVE_NODES, MOVE_NODE, RESIZE_NODE,
    RENAME_NODE, REMOVE_NODE, CLEAR_CANVAS, SAVE_VIEWPORT, PRUNE_ORPHANS
}
enum class BOOKS : TaskCode{
    GET_BOOKS, ADD_BOOK, UPDATE_BOOK, DELETE_BOOK,
}
enum class BOOK : TaskCode{
    GET_BOOK, ADD_BOOK, UPDATE_BOOK, DELETE_BOOK, READ_BOOK
}
enum class CATEGORIES : TaskCode{
    GET_CATEGORIES, ADD_CATEGORY, UPDATE_CATEGORY, DELETE_CATEGORY,
}
enum class SETTINGS : TaskCode{
    GET_SETTINGS, UPDATE_SETTINGS, DELETE_SETTINGS,
}

enum class PROFILE : TaskCode{
    USER_PROFILE, UPDATE, DELETE , PROFILE_IMAGE,
    // 👤 31-Aug-2026 profile
    SET_USERNAME, CHECK_USERNAME, PUBLIC_PROFILE, SEARCH_PEOPLE
}

// 💬 31-Aug-2026 chat
enum class CHAT : TaskCode {
    CONVERSATIONS, OPEN_CONVERSATION, DELETE_CONVERSATION, HISTORY, OLDER, SEND, DELETE_MESSAGE, PEERS
}
